development:
  database: rapleaf_development
  adapter: mysql
  host: 127.0.0.1
  username: root
  password: 

test:
  database: rapleaf_test
  adapter: mysql
  host: 127.0.0.1
  username: root
  password:

workflow_db_test:
  database: workflow_docker_env
  adapter: mysql
  host: 127.0.0.1
  username: root
  password:
  port: 31313

workflow_ui_jetty_db_test:
  database: workflow_docker_env
  adapter: mysql
  host: 127.0.0.1
  username: root
  password:
  port: 31313
