login: &login
  adapter: mysql2
  username: root
  password:
  endcoding: utf8
  reconnect: true
  # socket: /tmp/mysql.sock
  host: 127.0.0.1

workflow_development:
  <<: *login
  database: workflow_db_development

workflow_test:
  <<: *login
  database: workflow_db_test

development:
  <<: *login
  database: workflow_db_development

test:
  <<: *login
  database: workflow_db_test
