databases_namespace: com.liveramp.databases.workflow_db
databases: 
  -
    root_namespace: com.liveramp.databases.workflow_db
    db_name: WorkflowDb
    schema_rb: databases/workflow_db/db/schema.rb
    models: databases/workflow_db/app/models
